[hk4e]
resource_path = "/usr/local/game_hk4e/resources/GameDataConfigTable"
gacha_history_server = "https://hk4e.flswld.com/api/v1"

[logger]
level = "DEBUG"
method = "CONSOLE"
track_line = true

[air]
addr = "air"
port = 8086
service_name = "game-hk4e-app"

[light]
port = 10006

[database]
url = "mongodb://mongo:27017"

[mq]
nats_url = "nats://nats1:4222,nats://nats2:4222,nats://nats3:4222"
