http_port = 8080

[hk4e]
kcp_addr = "127.0.0.1"
kcp_port = 22103

[logger]
level = "DEBUG"
mode = "BOTH"
track = true
max_size = 10485760

[database]
url = "mongodb://mongo:27017"

[mq]
nats_url = "nats://nats:4222"
