http_port = 9005

[hk4e]
kcp_addr = "hk4e.flswld.com"
kcp_port = 22103

[logger]
level = "DEBUG"
method = "CONSOLE"
track_line = true

[air]
addr = "air"
port = 8086
service_name = "hk4e-gateway"

[light]
port = 10005

[database]
url = "mongodb://mongo:27017"

[mq]
nats_url = "nats://nats1:4222,nats://nats2:4222,nats://nats3:4222"
