[hk4e]
kcp_addr = "127.0.0.1" # 该地址只用来注册到节点服务器 并非网关本地监听地址 本地监听为0.0.0.0
kcp_port = 22103
client_proto_proxy_enable = false
version = "320"

[logger]
level = "DEBUG"
mode = "BOTH"
track = true
max_size = 10485760

[mq]
nats_url = "nats://nats:4222"
