http_port = 9001

[logger]
level = "DEBUG"
method = "CONSOLE"
track_line = true

[air]
addr = "air"
port = 8086
service_name = "water-auth"

[database]
url = "root:flswld@(mysql:3306)/annie_water?charset=utf8&parseTime=True&loc=Local"

[light]
port = 10002
