[hk4e]
client_proto_proxy_enable = false
resource_path = "./GameDataConfigTable"
game_data_config_path = "./game_data_config"
gacha_history_server = "https://hk4e.flswld.com/api/v1"

[logger]
level = "DEBUG"
mode = "BOTH"
track = true
max_size = 10485760

[database]
url = "mongodb://mongo:27017"

[redis]
addr = "redis:6379"
password = ""

[mq]
nats_url = "nats://nats:4222"
