http_port = 8080

[hk4e]
kcp_addr = "hk4e.flswld.com"
kcp_port = 22103
login_sdk_url = "https://api.flswld.com/api/v1/auth/login"

[logger]
level = "DEBUG"
method = "CONSOLE"
track_line = true

[database]
url = "mongodb://mongo:27017"
