http_port = 9002

[logger]
level = "DEBUG"
method = "CONSOLE"
track_line = true

[air]
addr = "air"
port = 8086
service_name = "annie-user-app"

[database]
url = "root:flswld@(mysql:3306)/annie_user?charset=utf8&parseTime=True&loc=Local"

[light]
port = 10003
