http_port = 80

[logger]
level = "DEBUG"
method = "CONSOLE"
track_line = true

[air]
addr = "air"
port = 8086
service_name = "wind-gateway"

[[routes]]
service_name = "water-auth"
service_predicates = "/api/v1/auth"
strip_prefix = 2

[[routes]]
service_name = "annie-user-app"
service_predicates = "/api/v1/user"
strip_prefix = 2

[[routes]]
service_name = "annie-wxmp-app"
service_predicates = "/api/v1/wxmp"
strip_prefix = 2

[[routes]]
service_name = "gm-hk4e-app"
service_predicates = "/api/v1/gm"
strip_prefix = 2
